python_tests(
    dependencies=[
        "src/python/my-subproject:my_subproject_distribution",
        "src/python/my-subproject:poetry#pydantic",
        "src/python/my-subproject:poetry#pyzmq"
    ]
)
